[package]
name = "heartbeat"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
